'use strict';var $jd=new w(null,"parent-uri","parent-uri",-371819908);hK.set("app.thumbnail-renderer",jK(vz));var akd=""+(AK??"");
function bkd(a){return GL(function(b){var c=new Image;sK(c,"onload",function(){b.next(c);return b.complete()});sK(c,"crossOrigin","anonymous");sK(c,"onerror",function(d){return b.error(d)});sK(c,"onabort",function(){var d=pi("operation aborted",eh.C(B([new l(null,3,[It,zQa,Ak,Y_a,dp,"operation aborted"],null),null])),null);return b.error(d)});sK(c,"src",a);return function(){sK(c,"src","");sK(c,"onload",null);sK(c,"onerror",null);return sK(c,"onabort",null)}})}
function ckd(a){return fM(uwb,cM(Dw,xM(new l(null,5,[fv,a,Ow,Zy,Uy,Iz,Ew,A1a,JCa,!0],null))))}function dkd(a){var b=FM(a,"href");return n(b)?cM(function(c){NM(a,"href",c);return a},ckd(b)):TL()}function ekd(a,b){var c=a.documentElement;var d=a.createElementNS("http://www.w3.org/2000/svg","style");IM(d,a.createTextNode(b));return IM(c,d)}
function fkd(a,b){return pM(nM(of(ekd,a),iM(function(c,d){var e=C(d,0,null);d=C(d,1,null);return wC(c,e,d)},b,fM(function(c){return cM(function(d){return new J(null,2,5,M,[c,d],null)},ckd(c))},cM(Tc,RL(Ch(/url\((https?:\/\/[^)]+)\)/,b)))))))}function gkd(a,b){return $L(B([pM(fM(dkd,RL(Zwb(a,"image")))),fkd(a,b),VL(a)]))}function hkd(a){return(new DOMParser).parseFromString(a,"image/svg+xml")}function ikd(a){a=a.documentElement;return(new XMLSerializer).serializeToString(a)}
function jkd(a,b,c){a=hkd(a);return cM(ikd,cM(function(d){var e=d.documentElement,g=FM(e,"width");e=FM(e,"height");if(!n(iD(g,e))){g=d.documentElement;e=FM(d.documentElement,"viewBox");if("string"===typeof e){var h=yC(e,/\s+/);C(h,0,null);C(h,1,null);e=C(h,2,null);h=C(h,3,null);e=fD(e,0);h=fD(h,0);var m=e/h;h=e>h?new J(null,2,5,M,[c,1/m*c],null):new J(null,2,5,M,[c*m,c],null)}else h=null;e=C(h,0,null);h=C(h,1,null);NM(g,"width",""+(e??""));NM(g,"height",""+(h??""))}return d},gkd(a,b)))}
function kkd(a){return GL(function(b){var c=uK.createElement("canvas");c.width=a.width;c.height=a.height;c.getContext("bitmaprenderer").transferFromImageBitmap(a);c.toBlob(function(d){b.next(d);return b.complete()});return mf(null)})}
function lkd(a){var b=H$a(a.width,300);return fM(kkd,fM(function(c){return nM(function(){return wwb(c)},fM(function(d){return createImageBitmap(d,{resizeWidth:b,resizeQuality:"medium"})},bkd(c)))},cM(vM,cM(function(c){return vwb(c,"image/svg+xml")},jkd(a.data,a.styles,b)))))}function mkd(a){var b=a.data;if(qC(akd,a.origin)){a=b.id;var c=b.payload;b=b.scope;return null!=c&&x.j(b,"penpot/thumbnail-renderer")?ML(of(nkd,a),of(okd,a),lkd(c)):null}return null}
function pkd(a,b,c){a={id:a,type:b,scope:"penpot/thumbnail-renderer",payload:c};return window===parent?null:parent.postMessage(a,akd)}function nkd(a,b){return pkd(a,"success",b)}function okd(a,b){return pkd(a,"failure",ri(b))}
function qkd(){window.addEventListener("message",mkd);pkd(null,"ready",null);if(iK("app.thumbnail-renderer",nm)){var a=function(){return new Qh(function(){return new J(null,3,5,M,[new J(null,2,5,M,[dp,"initialized"],null),new J(null,2,5,M,[b7a,""+(AK??"")],null),new J(null,2,5,M,[$jd,""+(akd??"")],null)],null)})}(),b=lK();fK(function(){var c=r(a),d=Uf.j(EC,c);c=TC.g(eh.C(B([null,null])));c=new l(null,7,[Mn,c,vA,b,Xv,d,ik,wG(),wq,new Qh(function(){return kK(d)}),Vp,"app.thumbnail-renderer",Ht,nm],
null);return Bf.j(gK,mf(c))})}return null}ma("app.thumbnail_renderer.init",qkd);qkd();
//# sourceMappingURL=thumbnail-renderer.0c302e30c.js.map
